const allClasses = [{className: 'Behind the Scenes of a Freshman at UIUC', time: '10:00am-10:50am', room: '0216', capacity: 30, description: 'An insider\'s perspective on navigating the exciting journey of freshman year at the University of Illinois at Urbana-Champaign (UIUC)! Throughout this semester-long exploration, you will delve into various aspects of campus life, gaining invaluable insights into dorm food, dorm halls, classes, clubs, student life, and fun activities to do on campus.'},
                    {className: 'WCS: Developing a Problem Solving Mindset in CS', time: '10:00am-10:50am', room: '1214', capacity: 20, description: 'Learn what it\'s like to problem solve and think critically about challenging issues as a computer scientist and engineer! Join us for an interactive session where you will learn the thought process behind iterative programming and developing, debugging, and thorough testing while following along and completing a “machine project” of your own!'},
                    {className: 'RPG Game Development using Javascript with Codédex', time: '10:00am-10:50am', room: '1302', capacity: 30, description: 'Build an RPG Game from top-to-bottom using Javascript Libraries! Learn about Game Design, Art, Music, and Production for a simple RPG game, and how you can use Codédex to learn Javascript and level up your coding knowledge!'},
                    {className: 'Computational Media!', time: '10:00am-10:50am', room: '1304', capacity: 20, description: 'An overview of how computer science is being used in media today! You\'ll learn about the different applications of computer science in media, such as audio, images, and video. Later,  you\'ll experiment with different audio and image algorithms. '},
                    {className: 'Introduction to Graph Theory: Graph Theory in the Real World ', time: '10:00am-10:50am', room: '2102', capacity: 10, description: 'Unlock the power of graph theory through learning essential graph algortihms and their real-life applications to enhance your problem solving skills'},
                    {className: 'Vim: CLI editing like a pro', time: '10:00am-10:50am', room: '2124', capacity: 15, description: 'Become an effective programmer by learning command line editing tools! '},
                    {className: 'Cybersecurity Ninja Training ', time: '10:00am-10:50am', room: '2405', capacity: 20, description: 'Learn the various aspects of computer security by hacking through a fun, interactive narrative!'},
                    {className: 'Programming Killer AI Bots ', time: '10:00am-10:50am', room: '2406', capacity: 20, description: 'Teach a program how to intelligently play borad games such as chess, checkers, or scrabble through programming!'},
                    {className: 'Inside the Mind of a Hacker', time: '10:00am-10:50am', room: '2407', capacity: 15, description: 'Launch into cybersecurity with a beginner-friendly introduction to the adversarial mindset to learn how to think like a hacker.'},
                    {className: 'Adding Numbers with Circuits!', time: '10:00am-10:50am', room: '3102', capacity: 12, description: 'Learn how a 2-bit binary adder circuit works! In this class,  you\'ll be able to wire up your own circuit to add numbers! '},
                    {className: 'Creating Your Own Personal Website', time: '10:00am-10:50am', room: '3124', capacity: 20, description: 'Get an crash-course in creating, personalizing, and sharing your own website to showcase yourself!'},
                    {className: 'Wordle with a Twist ', time: '10:00am-10:50am', room: '3401', capacity: 20, description: 'Just a little bit of code can do a lot! Use Python to customize Wordle to what you want it to be!'},
                    {className: 'Ardunio Lightshow ', time: '10:00am-10:50am', room: '4102', capacity: 12, description: 'Learn how to use Arduino in a bunch of different ways through computer science concepts, with a finale of a free-for-all light show!'},
                    {className: 'What is AI? Answers to the Big Questions!', time: '11:00am-11:50am', room: '0216', capacity: 20, description: 'AI is more vast and applicable than you thought...Learn about what AI is, how it works, and its applications!'},
                    {className: 'Intro to Quantum Computing', time: '11:00am-11:50am', room: '1214', capacity: 20, description: 'Get a high-level intro to Quantum Computing! How is it different from Classical Computing? What are its applications?'},
                    {className: 'Circuits to Code: A Primer on Computer Architecture', time: '11:00am-11:50am', room: '1302', capacity: 20, description: 'A fly-by overview of the basics of computer architecture. You\'ll learn what computer architecture is and what you can expect from a computer engineering degree at UIUC. Work your way through logic gates and binary to understand the basics of an 8-bit computer.'},
                    {className: 'Seeking Opportunities at UIUC', time: '11:00am-11:50am', room: '1304', capacity: 20, description: 'The ability to recognize and capitalize on opportunities is incredibly important and this course aims to help you do so within the school setting and explore specific opportunities at U of I. We are here to empower you and help you identify opportunities and establish meaningful connections! '},
                    {className: 'WCS: How to be a Woman in CS', time: '11:00am-11:50am', room: '1404', capacity: 30, description: 'What is it like being a woman in computer science and engineering? Join us for an interactive session where we\'ll show you how to build a support system and community, increase your own confidence, deal with failure, as well as seek out career and mentorship opportunities. This will be followed by personal stories of women in CS at UIUC along with an open Q&A Panel!'},
                    {className: 'Introduction to Data Structures ', time: '11:00am-11:50am', room: '2102', capacity: 10, description: 'This class will focus on some real problems you face and guide you on how you can use data structures in software to solve them! '},
                    {className: 'Automate the Boring Stuff with Python! ', time: '11:00am-11:50am', room: '2124', capacity: 15, description: 'In this class, you\'ll learn how to use Python to write programs that take minutes to do things that would take hours to do by hand - no prior programming experience required! Once you\'ve mastered the basics of programming, you\'ll create Python programs that effortlessly perform useful and impressive feats of automation to '},
                    {className: 'CS outside the classroom', time: '11:00am-11:50am', room: '2405', capacity: 20, description: 'Take a deep dive into how recruitment season for internships and careers works and an overview of Engineering RSOs on campus!'},
                    {className: 'Intro to Python', time: '11:00am-11:50am', room: '2406', capacity: 20, description: 'Start your programming journey with Python! Learn about Jupyter Notebooks, solve open-ended problems, and get a general intro to Python.'},
                    {className: 'Circles and Lines: Introduction to Graph Theory with Real-Life Applications', time: '11:00am-11:50am', room: '2407', capacity: 15, description: 'Dive into graph theory! Get an overview of a vast number of topics in graph theory (connectivity, coloring, path-finding, etc), and applications to other fields (linguistics, neuroscience, sociology, etc).'},
                    {className: 'Robotics for IOT', time: '11:00am-11:50am', room: '3102', capacity: 10, description: 'Learn about the basics of robotics through both physical examples as well as the theory behind them!'},
                    {className: 'Build Spotify Wrapped From Scratch! ', time: '11:00am-11:50am', room: '3124', capacity: 20, description: 'How to use the Spotify API and React to build a simpler version of Spotify Wrapped! You\'ll get the chance to play around with customizing your own websites and writing your first API calls!'},
                    {className: 'Theoretical Foundations of Functional Programming', time: '11:00am-11:50am', room: '3401', capacity: 20, description: 'Get a crash course into the theory of Functional Programming through demos, interactive exercises, and the lambda calculus behind it!'},
                    {className: 'Introduction to Computer Graphics', time: '11:00am-11:50am', room: '4102', capacity: 15, description: 'Learn the basics of computer graphics through Rasters, Rasterization, and WebGL!'},
                    {className: 'Recursion and Induction', time: '2:00pm-3:00pm', room: '0216', capacity: 20, description: 'Explore the concepts of recursion and induction by tackling problems and designing algorithms using these approaches.'},
                    {className: 'CybersecYOUrity: A Guide to Navigating Your Digital World through Cybersecurity Adventures and Pop Culture', time: '2:00pm-3:00pm', room: '1214', capacity: 20, description: 'Learn why cybersecurity is important and how it affects YOU. Understand the realities of how cybersecurity works in the real world!'},
                    {className: 'Software to Silicon: How Your Code Actually Works', time: '2:00pm-3:00pm', room: '1302', capacity: 20, description: 'Behind every program are layers and layers of complicated systems! This course will let you see what goes under the hood of your computer program.'},
                    {className: 'WCS: Cyphers in Computer Science', time: '2:00pm-3:00pm', room: '1304', capacity: 20, description: 'Join us for a fun, interactive session on the basics of cryptography and cyphers! We will present a tutorial on how to get started with encryption through Python followed by an interactive workshop where you will learn more about the algorithms that go behind cyphers in computer science and engineering!'},
                    {className: 'How to get a SWE Internship ', time: '2:00pm-3:00pm', room: '1404', capacity: 20, description: 'A beginner\'s guide to getting a SWE internship, including interview prep, networking, resume format, applying online, and deciding where to apply. This course comes with a light presentation, a fun activity, and an open-ended conversation with any questions you have.'},
                    {className: 'Intro to Algorithms', time: '2:00pm-3:00pm', room: '2102', capacity: 15, description: 'Explore algorithms in computer science! '},
                    {className: 'Binary Search Analysis and Applications', time: '2:00pm-3:00pm', room: '2124', capacity: 15, description: 'Learn the intracacies of Binary Search, and the multitucde of problem-solving applications it can have, especially in coding interviews!'},
                    {className: 'AI in our lives', time: '2:00pm-3:00pm', room: '2405', capacity: 20, description: 'Explore how AI plays a role in our lives while playing around with some student AI projects! '},
                    {className: 'Resource Wizardry: Unlocking Academic Magic', time: '2:00pm-3:00pm', room: '2406', capacity: 20, description: 'How to make the most out of the resources offered in CS at UIUC! Tips and tricks for on-campus tutoring, office hours, and website-based learning. '},
                    {className: 'Intro to Machine Learning with Kaggle Titantic Dataset', time: '2:00pm-3:00pm', room: '2407', capacity: 20, description: 'Learn the basics of machine learning using Python and how to use Kaggle datasets to your advantage'},
                    {className: 'Intro to Javascript with p5.js', time: '2:00pm-3:00pm', room: '3102', capacity: 10, description: 'Get an intro to the JavaScript Language in the context of p5.js and learn how to creatively make your own graphics with it!'},
                    {className: 'Taste the Flavors of Computer Science', time: '2:00pm-3:00pm', room: '3124', capacity: 15, description: 'Find the different pathways to be pursued in computer science such as SWE, Product Management, Quantitative Trading, and more, learning through interactive examples!'},
                    {className: 'Your Spotify Wrapped API', time: '2:00pm-3:00pm', room: '3401', capacity: 15, description: 'A hands-on tutorial on how to use the Spotify API! In this class, you\'ll write a Python program that mimics your Spotify Wrapped.'},
                    {className: 'Personal Website Devlopment', time: '2:00pm-3:00pm', room: '4102', capacity: 15, description: 'A workshop on creating your personal website! By combining interpersonal and technical skills,  this workshop will teach you personal branding and learning from your peers while building your own website.'}]

allClasses.push(
    { className: 'Resource Wizardry: Unlocking Academic Magic', time: '12:30pm-1:15pm', room: 'zoom', capacity: 100, description: 'How to make the most out of the resources offered in CS at UIUC! Tips and tricks for on-campus tutoring, office hours, and website-based learning.' },
    { className: 'Data Structures - Stacks and queues', time: '12:30pm-1:15pm', room: 'zoom', capacity: 100, description: 'Learn about stacks and queues, two fundamental data structures used in computer science.' },
    { className: 'Vim: CLI editing like a pro', time: '12:30pm-1:15pm', room: 'zoom', capacity: 100, description: 'Become an effective programmer by learning command line editing tools!' },
    { className: 'RPG Game Development using Javascript with Codédex', time: '12:30pm-1:15pm', room: 'zoom', capacity: 100, description: 'Build an RPG Game from top-to-bottom using Javascript Libraries!' },
    { className: 'Intro to Graph Theory', time: '12:30pm-1:15pm', room: 'zoom', capacity: 100, description: 'Unlock the power of graph theory through learning essential graph algorithms and their real-life applications to enhance your problem-solving skills.' },
    { className: 'Inside the Mind of a Hacker', time: '12:30pm-1:15pm', room: 'zoom', capacity: 100, description: 'Launch into cybersecurity with a beginner-friendly introduction to the adversarial mindset to learn how to think like a hacker.' },
    { className: 'Programming Killer AI Bots', time: '12:30pm-1:15pm', room: 'zoom', capacity: 100, description: 'Teach a program how to intelligently play board games such as chess, checkers, or scrabble through programming!' }
);

allClasses.push(
    { className: 'What is AI? Answers to the Big Questions!', time: '12:30pm-1:15pm', room: 'zoom', capacity: 100, description: 'Explore the fundamental questions and concepts behind Artificial Intelligence.' },
    { className: 'Behind the scenes of a freshman at UIUC', time: '12:30pm-1:15pm', room: 'zoom', capacity: 100, description: 'Get an insider\'s perspective on the life of a freshman at UIUC.' },
    { className: 'Intro to Graph Theory (Real World Problems)', time: '12:30pm-1:15pm', room: 'zoom', capacity: 100, description: 'Discover how graph theory can be applied to solve real-world problems.' },
    { className: 'Your Spotify Wrapped API', time: '12:30pm-1:15pm', room: 'zoom', capacity: 100, description: 'Learn how to use the Spotify API to create your own personalized Spotify Wrapped experience.' },
    { className: 'Software to Silicon: How Your code Actually works?', time: '12:30pm-1:15pm', room: 'zoom', capacity: 100, description: 'Dive into the inner workings of software and hardware to understand how your code is executed.' },
    { className: 'Create Your Own Wordle with a Twist!', time: '1:30pm-2:15pm', room: 'zoom', capacity: 100, description: 'Put a unique spin on the popular word-guessing game Wordle by creating your own version.' }
);


allClasses.forEach((c, i) => c.index = i);

const inPersonMorningClassesFirst = allClasses.slice(0, 13);
const inPersonMorningClassesSecond = allClasses.slice(13, 27);
const inPersonAfternoonClasses = allClasses.slice(27, 42);
const virtualMorningClasses = allClasses.slice(42, 49);
const virtualAfternoonClasses = allClasses.slice(49, 54);

export { inPersonMorningClassesFirst, inPersonMorningClassesSecond, inPersonAfternoonClasses, virtualMorningClasses, virtualAfternoonClasses};
export default allClasses;