const allClasses = [
    // ==================== 10:00am - 10:50am (Day 1 In-Person) ====================
    {
      className: 'Build Your Own AI!',
      time: '10:00am-10:50am',
      room: 'Siebel 0216',
      capacity: 93,
      description: "How do self-driving cars work? How is ChatGPT so smart? Learn the answers to these questions by building your own computer vision neural network and diving into the applications of AI! No prior coding experience is necessary!",
      classIndex: 0,
      zoomLink: null,
    },
    {
      className: 'Recursion: A Non-tree-vial Introduction',
      time: '10:00am-10:50am',
      room: 'Siebel 0220',
      capacity: 48,
      description: "Think you understand a problem? What if solving it just meant solving a smaller version of itself? Recursion is one of the most elegant — and brain-bending — ideas in all of computer science, and this class is your guide to finally getting it (to get it, you must first get it). From factorial functions to fractal structures, from merge sort to traversing the very trees hiding in our title, we'll unpack how thinking recursively unlocks solutions that loops could only dream of. Warning: this class may cause you to think about thinking about thinking. Prerequisites: an open mind — and a base case. Materials: pen and paper or device.",
      classIndex: 2,
      zoomLink: null,
    },
    {
      className: '"Git" Gud at Version Control',
      time: '10:00am-10:50am',
      room: 'Siebel 2102',
      capacity: 14,
      description: "Learn how to collaborate on projects large and small using Git, the industry standard tool for versioning and sharing code! This is a hands-on class where students will learn the fundamentals of the Git version control system, workflows and how to use it for collaboration and contributing to OSS. Soft requirements: Laptop with internet connectivity (ideally something Unix based), basic proficiency with CLI. Materials: device.",
      classIndex: 3,
      zoomLink: null,
    },
    {
      className: 'How Apps Update Instantly: Behind the Scenes of Live Data',
      time: '10:00am-10:50am',
      room: 'Siebel 2124',
      capacity: 20,
      description: "How do apps update instantly without refreshing? From live maps to multiplayer games, we'll explore how data moves across the internet in real time. You'll see how engineers balance speed and reliability, what happens when things go wrong, and how real systems track live data in the real world.",
      classIndex: 4,
      zoomLink: null,
    },
    {
      className: 'Quantum Computing for High Schoolers',
      time: '10:00am-10:50am',
      room: 'Siebel 2406',
      capacity: 48,
      description: "Learn what you need to know about an exciting revolution in technology! This course includes no mathematics or coding. Instead, enjoy exploring what quantum computing is actually about, the weird rules of quantum physics, and how this all changes computing in the future. We will also play a game from Google Quantum AI and have a casual Q&A! Materials: device.",
      classIndex: 5,
      zoomLink: null,
    },
    {
      className: 'Cryptography from Scratch',
      time: '10:00am-10:50am',
      room: 'Siebel 2407',
      capacity: 20,
      description: "We will study the interesting problem of constructing non-reversable functions and analyze some functions that fulfill this property. Encryption and digests will fall out of this analysis, and we will compose those primitives to craft both attack- and eavesdropper-resistant communication channel, and digital identity validation. Then we will see how cryptography is used to solve specific problems we face today.",
      classIndex: 6,
      zoomLink: null,
    },
    {
      className: 'Introduction to Web Development with React',
      time: '10:00am-10:50am',
      room: 'Siebel 3401',
      capacity: 22,
      description: "Ever wonder how modern, interactive websites are built? We'll briefly review the basics of HTML, CSS, and vanilla JavaScript, and then dive directly into React to see why it's the industry standard for building user interfaces. Includes a live coding demonstration! Materials: device.",
      classIndex: 7,
      zoomLink: null,
    },
    {
      className: 'Intro to Game Development w/ Roblox Studio',
      time: '10:00am-10:50am',
      room: 'Siebel 3124',
      capacity: 20,
      description: "Ever wanted to know what kind of thinking goes into Game development? In this class, we provide a general introduction to game development concepts, including System Design, Raycasting, Anti-cheat, and State Machines, using Super Mario Bros. Level 1-1 as a case study. No knowledge of Roblox Studio required, but an understanding of programming is very helpful. Materials: device.",
      classIndex: 9,
      zoomLink: null,
    },
    {
      className: 'The Design Behind Every App You Love: An Intro to UI/UX',
      time: '10:00am-10:50am',
      room: 'Siebel 4102',
      capacity: 14,
      description: "Ever wonder why you can spend three hours scrolling TikTok without getting bored, but you can't find the 'close' button on a single pop-up? Bad design is everywhere, and you'll learn how to spot it by racing head-to-head to escape a site built with intentionally broken design. You'll dive into the psychology of why certain designs work and why others fail, then use Figma to build a page that anyone can use. No coding experience needed! Laptop required. Materials: device.",
      classIndex: 10,
      zoomLink: null,
    },
    {
      className: 'Baby\'s First Vim Motions',
      time: '10:00am-10:50am',
      room: 'Siebel 4407',
      capacity: 20,
      description: "Have you heard of Neovim but never actually tried it? Now's your chance to give it a shot and experience the power of modal editing! In this beginner-friendly course, you'll learn the basics of Neovim and do practical exercises to get familiar with various motions. Get ready to say \"bye bye VSCode, hello Neovim!\" Materials: device.",
      classIndex: 11,
      zoomLink: null,
    },
    {
      className: 'Programming Language Semantics',
      time: '10:00am-10:50am',
      room: 'Siebel 1302',
      capacity: 48,
      description: "Before we can reason about programs, we need a clear way to describe what code means. In this class, we'll study an approach called big-step operational semantics: a formal system for describing how programs execute. Then, we'll use it to model a simple programming language.",
      classIndex: 12,
      zoomLink: null,
    },
    {
      className: 'Red-teaming: Finding the Cracks in AI',
      time: '10:00am-10:50am',
      room: 'Siebel 1404',
      capacity: 200,
      description: "Think you can outsmart a chatbot? Come experiment hands-on with real AI apps and try to break them — no coding required. We'll get hands-on with why AI safety is harder than it looks, why people are working hard to fix it, and how you can get involved! Materials: device.",
      classIndex: 13,
      zoomLink: null,
    },
    {
      className: 'From High School to Hired: Resumes, Internships, and Breaking into Tech',
      time: '10:00am-10:50am',
      room: 'Siebel 2405',
      capacity: 70,
      description: "Enjoying the few months of fun after the last 4 years of SAT prep, millions of extracurriculars, and the 67 college essays you had to write? Dooming over filling out an internship application? In this one-hour session, us former FAANG interns will review your resume, prep you for the trenches of intern recruiting, and help you learn how to max out your networking aura. Just bring yourself, a resume (can just be a draft!), and a hunger for your future career gains. Materials: recommended resume.",
      classIndex: 14,
      zoomLink: null,
    },
    {
      className: 'Intro to the Engineering Pathways Program',
      time: '10:00am-10:50am',
      room: 'Siebel 4124',
      capacity: 20,
      description: "The Engineering Pathways Program is a community college transfer plan that offers guaranteed admission into the Grainger College of Engineering for your major of choice, including Computer Science. It is an incredibly viable option for saving money while still getting world-class education and professional opportunities. In this session, you'll learn about the application process, eligibility requirements and other important information. I'll also include advice from myself and other Pathways CS students about school and securing a successful career in tech.",
      classIndex: 15,
      zoomLink: null,
    },
    {
      className: 'Code Meets Cosmos',
      time: '10:00am-10:50am',
      room: 'Siebel 1304',
      capacity: 46,
      description: "The Three-Body problem. Maybe you have watched the Netflix show or heard of this physics problem that stumps researchers today. In Code Meets Cosmos, we will simulate the Three-Body problem ourselves and see why it remains unsolved to this day. No prior physics knowledge is needed! Materials: device.",
      classIndex: 16,
      zoomLink: null,
    },
  
    // ==================== 11:00am - 11:50am (Day 1 In-Person) ====================
    {
      className: 'From Domino Puzzles to Math and Computer Science',
      time: '11:00am-11:50am',
      room: 'Siebel 0218',
      capacity: 47,
      description: "How many ways can you cover a chessboard with dominos? What if we roll that board into a cylinder or a donut? The results of domino tiling on different surfaces is well established, but results using more complex shapes are still active areas of research, with deep relations to other fields of Mathematics. This course aims to provide an overview of this field with rich examples and proof. Materials: paper and pen.",
      classIndex: 18,
      zoomLink: null,
    },
    {
      className: 'Intro to LLMs',
      time: '11:00am-11:50am',
      room: 'Siebel 0220',
      capacity: 48,
      description: "Learn how LLMs work at a fundamental level. Explore the inner workings of the transformer architecture and attention mechanism. Build and train your own LLM from scratch with Python and PyTorch. Welcome beginners and advanced! Materials: device.",
      classIndex: 19,
      zoomLink: null,
    },
    {
      className: '"Git" Gud at Version Control',
      time: '11:00am-11:50am',
      room: 'Siebel 2102',
      capacity: 14,
      description: "Learn how to collaborate on projects large and small using Git, the industry standard tool for versioning and sharing code! This is a hands-on class where students will learn the fundamentals of the Git version control system, workflows and how to use it for collaboration and contributing to OSS. Soft requirements: Laptop with internet connectivity (ideally something Unix based), basic proficiency with CLI. Materials: device.",
      classIndex: 20,
      zoomLink: null,
    },
    {
      className: 'Teaching Computers to Think with 1s and 0s',
      time: '11:00am-11:50am',
      room: 'Siebel 2124',
      capacity: 20,
      description: "Ever wondered how computers actually work under the hood? In this class, we'll explore how everything from text messages to videos is built from simple 1s and 0s. You'll discover how computers store, process, and sometimes mess up data, and see how these ideas power every app you use today.",
      classIndex: 21,
      zoomLink: null,
    },
    
    {
      className: 'Coding Music',
      time: '11:00am-11:50am',
      room: 'Siebel 2407',
      capacity: 20,
      description: "Explore how music and coding come together! In this beginner-friendly workshop, you'll use TunePad to create your own songs while learning basic programming concepts like functions, loops, and sequencing. No prior experience needed! Just bring your laptop, a pair of headphones, and get ready to make music with code! Materials: device, headphones recommended.",
      classIndex: 23,
      zoomLink: null,
    },
    {
      className: 'Introduction to Data Science and Machine Learning with Python',
      time: '11:00am-11:50am',
      room: 'Siebel 2405',
      capacity: 70,
      description: "Curious about data science but not sure where to start? This beginner-friendly course will introduce you to the fundamentals of data science and machine learning using Google Colab, no setup required! You'll follow along with live coding exercises to learn Python basics, explore real datasets, create visualizations, and build your first simple machine learning models. Come ready to learn by doing and see how data turns into insights! Materials: device, active Google account.",
      classIndex: 24,
      zoomLink: null,
    },
    {
      className: 'What the Heck is a Programming Language?',
      time: '11:00am-11:50am',
      room: 'Siebel 3102',
      capacity: 14,
      description: "Programming isn't just math—it's high-precision writing for a \"smart but difficult\" reader. We will explore the philosophy of language design, from grammar quirks like 0-indexing to \"chill\" vs. \"strict\" typing. Finally, we'll look at the \"layers of paranoia\" that define modern coding, where we can't trust the ecosystem, the runtime, or even ourselves.",
      classIndex: 25,
      zoomLink: null,
    },
    {
      className: 'Intro to Game Development w/ Roblox Studio',
      time: '11:00am-11:50am',
      room: 'Siebel 3124',
      capacity: 20,
      description: "Ever wanted to know what kind of thinking goes into Game development? In this class, we provide a general introduction to game development concepts, including System Design, Raycasting, Anti-cheat, and State Machines, using Super Mario Bros. Level 1-1 as a case study. No knowledge of Roblox Studio required, but an understanding of programming is very helpful. Materials: device.",
      classIndex: 26,
      zoomLink: null,
    },
    {
      className: 'CS Explained Through Anime and Shows',
      time: '11:00am-11:50am',
      room: 'Siebel 3401',
      capacity: 22,
      description: "Ever wanted to learn what Computer Science is all about? Well now you can learn about Computer Science through Anime and Shows! This will be a course where you get to talk about and learn from your favorite shows through the lens of Computer Science. Learn about how computer scientists think about problems! Materials: device.",
      classIndex: 27,
      zoomLink: null,
    },
    {
      className: 'The Design Behind Every App You Love: An Intro to UI/UX',
      time: '11:00am-11:50am',
      room: 'Siebel 4102',
      capacity: 14,
      description: "Ever wonder why you can spend three hours scrolling TikTok without getting bored, but you can't find the 'close' button on a single pop-up? Bad design is everywhere, and you'll learn how to spot it by racing head-to-head to escape a site built with intentionally broken design. You'll dive into the psychology of why certain designs work and why others fail, then use Figma to build a page that anyone can use. No coding experience needed! Laptop required. Materials: device.",
      classIndex: 28,
      zoomLink: null,
    },
    {
      className: 'Imposter Syndrome 101: Navigating the "I Don\'t Belong" Bug',
      time: '11:00am-11:50am',
      room: 'Siebel 4124',
      capacity: 20,
      description: "Ever feel like you're just \"getting lucky\" or that you aren't a \"real\" programmer? This session explores the psychological phenomenon of Imposter Syndrome. We'll discuss why it's so common in CS, how to identify it, and practical strategies to build genuine confidence while navigating the most difficult paths in tech.",
      classIndex: 29,
      zoomLink: null,
    },
    {
      className: 'Baby\'s First Vim Motions',
      time: '11:00am-11:50am',
      room: 'Siebel 4407',
      capacity: 20,
      description: "Have you heard of Neovim but never actually tried it? Now's your chance to give it a shot and experience the power of modal editing! In this beginner-friendly course, you'll learn the basics of Neovim and do practical exercises to get familiar with various motions. Get ready to say \"bye bye VSCode, hello Neovim!\" Materials: device.",
      classIndex: 30,
      zoomLink: null,
    },
    {
      className: 'How to Bake One Million Cakes: A Guide to Algorithm Design',
      time: '11:00am-11:50am',
      room: 'Siebel 1302',
      capacity: 48,
      description: "How do you sort a class in order of birthdays? How should a group of people exchange phone numbers? Through interactive real-life examples, explore common algorithms such as sorting lists, parallel communication protocols, and more. This course will teach core principles of efficient algorithm design including accuracy, time complexity, storage cost, and parallelization. Materials: pen and paper.",
      classIndex: 31,
      zoomLink: null,
    },
    {
      className: 'Breaking In & Standing Out',
      time: '11:00am-11:50am',
      room: 'Siebel 1404',
      capacity: 200,
      description: "Learn how to break into the CS industry from two Google interns! Get an overview of what projects and resources to look out for, how to interview prep, and how to be successful at your internship! Some free swag will be provided thanks to the Google Ambassador Program. Please bring a resume if you wish for it to be reviewed. Materials: recommended resume.",
      classIndex: 32,
      zoomLink: null,
    },
    {
      className: 'Code Meets Cosmos',
      time: '11:00am-11:50am',
      room: 'Siebel 1304',
      capacity: 46,
      description: "The Three-Body problem. Maybe you have watched the Netflix show or heard of this physics problem that stumps researchers today. In Code Meets Cosmos, we will simulate the Three-Body problem ourselves and see why it remains unsolved to this day. No prior physics knowledge is needed! Materials: device.",
      classIndex: 33,
      zoomLink: null,
    },
  
    // ==================== 2:00pm - 2:50pm (Day 1 In-Person) ====================
    {
      className: 'Humanized Machine Learning',
      time: '2:00pm-2:50pm',
      room: 'Siebel 0216',
      capacity: 93,
      description: "Explore Machine Learning through a unique lens — your own brain. This class draws simple parallels between how models learn from data and how human experiences shape thinking and behavior. Discover why ML matters, how it works, and why it's an exciting path for future students in computer science. No prior experience needed! Laptop required. Materials: device, active Google account.",
      classIndex: 34,
      zoomLink: null,
    },
    {
      className: 'Intro to LLMs',
      time: '2:00pm-2:50pm',
      room: 'Siebel 0220',
      capacity: 48,
      description: "Learn how LLMs work at a fundamental level. Explore the inner workings of the transformer architecture and attention mechanism. Build and train your own LLM from scratch with Python and PyTorch. Welcome beginners and advanced! Materials: device.",
      classIndex: 36,
      zoomLink: null,
    },
    {
      className: 'Thinking Like a Computer: Sorting and Searching Algorithms',
      time: '2:00pm-2:50pm',
      room: 'Siebel 2102',
      capacity: 14,
      description: "How do computers search and organize huge amounts of data so quickly? In this interactive class, students will explore how sorting and searching algorithms work through demonstrations and activities, and learn how efficient algorithms allow computers to solve problems at massive scale. Materials: pen and paper.",
      classIndex: 37,
      zoomLink: null,
    },
    {
      className: 'Introduction to Data Science and Machine Learning with Python',
      time: '2:00pm-2:50pm',
      room: 'Siebel 2405',
      capacity: 70,
      description: "Curious about data science but not sure where to start? This beginner-friendly course will introduce you to the fundamentals of data science and machine learning using Google Colab, no setup required! You'll follow along with live coding exercises to learn Python basics, explore real datasets, create visualizations, and build your first simple machine learning models. Come ready to learn by doing and see how data turns into insights! Materials: device, active Google account.",
      classIndex: 38,
      zoomLink: null,
    },
    {
      className: 'How Your Computer Lies to You: An Introduction to Numerical Analysis',
      time: '2:00pm-2:50pm',
      room: 'Siebel 1304',
      capacity: 46,
      description: "This course will go over the basics of Numerical Analysis and is focused on making the topics approachable and interactive. It covers ways that computers misrepresent information, approximation methods, optimization, and also a bit of advice for prospective college students. Materials: optional note-taking materials.",
      classIndex: 39,
      zoomLink: null,
    },
    {
      className: 'How to Bake One Million Cakes: A Guide to Algorithm Design',
      time: '2:00pm-2:50pm',
      room: 'Siebel 1302',
      capacity: 48,
      description: "How do you sort a class in order of birthdays? How should a group of people exchange phone numbers? Through interactive real-life examples, explore common algorithms such as sorting lists, parallel communication protocols, and more. This course will teach core principles of efficient algorithm design including accuracy, time complexity, storage cost, and parallelization. Materials: pen and paper.",
      classIndex: 40,
      zoomLink: null,
    },
    {
      className: 'Breaking In & Standing Out',
      time: '2:00pm-2:50pm',
      room: 'Siebel 1404',
      capacity: 200,
      description: "Learn how to break into the CS industry from two Google interns! Get an overview of what projects and resources to look out for, how to interview prep, and how to be successful at your internship! Some free swag will be provided thanks to the Google Ambassador Program. Please bring a resume if you wish for it to be reviewed. Materials: recommended resume.",
      classIndex: 41,
      zoomLink: null,
    },
    {
      className: 'None to Billions -- Logic. Induction. Recursion.',
      time: '2:00pm-2:50pm',
      room: 'Siebel 3124',
      capacity: 20,
      description: "Once a month, under the full moon, computer science and philosophy align, creating a tremendously important subject known as formal logic. We'll begin with a basic overview of logic by looking at a number of puzzles, then move on to two difficult but related concepts: Induction and recursion. Through these ideas, we'll explore infinity, and you'll already get some prior experience for some of the most difficult computer science classes that the University has to offer.",
      classIndex: 43,
      zoomLink: null,
    },
    {
      className: 'Beyond the Classroom: Finding Your Community with RSOs in CS @ Illinois',
      time: '2:00pm-2:50pm',
      room: 'Siebel 3401',
      capacity: 22,
      description: "CS at Illinois is much more than classes, office hours, and coding assignments. Some of the most meaningful parts of college happen when you find the people, projects, and communities that make campus feel like home. In this session, we'll explore the many ways students get involved in CS outside the classroom, from hackathons and project teams to mentorship programs, identity-based communities, and organizations beyond CS entirely.",
      classIndex: 44,
      zoomLink: null,
    },
    {
      className: 'How to Think Like a Hacker',
      time: '2:00pm-2:50pm',
      room: 'Siebel 4407',
      capacity: 20,
      description: "How do hackers find and exploit vulnerabilities in software, and how do defenders stop them? In this beginner-friendly session, you'll be introduced to the security mindset: a way of thinking about systems from both the attacker's and defender's perspectives. Through interactive activities, you'll explore how real systems can be broken into and defended, and how red teams and blue teams approach security challenges. No security or computer science background required! Materials: optional note-taking materials.",
      classIndex: 45,
      zoomLink: null,
    },
    {
      className: 'How to Build Tech for Social Good!',
      time: '2:00pm-2:50pm',
      room: 'Siebel 4124',
      capacity: 20,
      description: "From identifying patterns in data to making information more accessible, computer science (CS) has so much potential for social impact! In this class, you'll learn how to identify a problem you care about and develop a solution to it with CS. Free snacks as well! Materials: device.",
      classIndex: 46,
      zoomLink: null,
    },
  
    // ==================== 12:30pm - 1:20pm (Day 2 Virtual) ====================
    {
      className: 'What the Heck is a Programming Language?',
      time: '12:30pm-1:20pm',
      room: 'Zoom',
      capacity: 100,
      description: "Programming isn't just math—it's high-precision writing for a \"smart but difficult\" reader. We will explore the philosophy of language design, from grammar quirks like 0-indexing to \"chill\" vs. \"strict\" typing. Finally, we'll look at the \"layers of paranoia\" that define modern coding, where we can't trust the ecosystem, the runtime, or even ourselves.",
      classIndex: 47,
      zoomLink: 'https://illinois.zoom.us/j/81963319818?pwd=HhQnPiaPIwPzgIae1kdLbXpmmKLzMH.1',
    },
    {
      className: 'Thinking Like a Computer: Sorting and Searching Algorithms',
      time: '12:30pm-1:20pm',
      room: 'Zoom',
      capacity: 100,
      description: "How do computers search and organize huge amounts of data so quickly? In this interactive class, students will explore how sorting and searching algorithms work through demonstrations and activities, and learn how efficient algorithms allow computers to solve problems at massive scale. Materials: pen and paper.",
      classIndex: 48,
      zoomLink: null,
    },
    {
      className: 'Introduction to Artificial Intelligence & Neural Networks',
      time: '12:30pm-1:20pm',
      room: 'Zoom',
      capacity: 100,
      description: "This 50-minute interactive session introduces high school students to Artificial Intelligence from a mathematical and conceptual perspective. Students will explore how neural networks work, participate in a guided hands-on activity, and learn how AI is studied and developed at the University of Illinois Urbana-Champaign. Materials: device.",
      classIndex: 49,
      zoomLink: "https://illinois.zoom.us/j/82009416374?pwd=3m7SPJXWUk7Mu5zG766MTxx9wLzZS8.1",
    },
    {
      className: 'Beyond the Keyboard: Navigating Digital Tech Project Management',
      time: '12:30pm-1:20pm',
      room: 'Zoom',
      capacity: 100,
      description: "Ever wonder what project managers actually do? Join this interactive lesson to learn the basics of balancing time, quality, and cost! Through hands-on simulations and fun activities, you'll explore Agile, Scrum, Gantt charts, and popular software. Discover how to plan projects, uncover exciting career paths, and review salary expectations. Materials: device.",
      classIndex: 50,
      zoomLink: "https://illinois.zoom.us/j/6133787845?pwd=wRnBhiGrsruZzCJ2f2IzcNWtV3kXjT.1",
    },
    {
      className: 'Baby\'s First Vim Motions',
      time: '12:30pm-1:20pm',
      room: 'Zoom',
      capacity: 100,
      description: "Have you heard of Neovim but never actually tried it? Now's your chance to give it a shot and experience the power of modal editing! In this beginner-friendly course, you'll learn the basics of Neovim and do practical exercises to get familiar with various motions. Get ready to say \"bye bye VSCode, hello Neovim!\" Materials: device.",
      classIndex: 52,
      zoomLink: 'https://illinois.zoom.us/j/83209842684?pwd=eNYGJIMOyIjXL87eI7Pio35TH3Aq7J.1',
    },
    {
      className: 'From High School to Hired: Resumes, Internships, and Breaking into Tech',
      time: '12:30pm-1:20pm',
      room: 'Zoom',
      capacity: 100,
      description: "In this one-hour session, us former FAANG interns will review your resume, prep you for the trenches of intern recruiting, and help you learn how to max out your networking aura. By the end of the workshop, you'll be fully ready to jumpstart your career and mog the competition. Just bring yourself, a resume (can just be a draft!), and a hunger for your future career gains. Materials: recommended resume.",
      classIndex: 53,
      zoomLink: 'https://illinois.zoom.us/j/85032539320?pwd=bjERarDHd0IWZJ3wjMDUanHaoVrcxM.1',
    },
    {
      className: 'Build Your Own AI!',
      time: '12:30pm-1:20pm',
      room: 'Zoom',
      capacity: 100,
      description: "How do self-driving cars work? How is ChatGPT so smart? Learn the answers to these questions by building your own computer vision neural network and diving into the applications of AI! No prior coding experience is necessary!",
      classIndex: 54,
      zoomLink: 'https://illinois.zoom.us/j/2156078854?pwd=a0F0dVRvTHJlZnVRNVJSVFNnVUNpdz09',
    },
    {
      className: 'Intro to Search Engines',
      time: '12:30pm-1:20pm',
      room: 'Zoom',
      capacity: 100,
      description: "Explore the system behind every search you make. We'll break down the three traditional steps; Crawl, Index, and Rank, and see why keyword matching is obsolete. Discover how Large Language Models (LLMs) like Gemini and ChatGPT are revolutionizing search by understanding context and intent, and examine the critical, unsolved problems of AI bias and hallucinations.",
      classIndex: 55,
      zoomLink: null,
    },
  
    // ==================== 1:30pm - 2:20pm (Day 2 Virtual) ====================
    {
      className: 'Red-teaming: Finding the Cracks in AI',
      time: '1:30pm-2:20pm',
      room: 'Zoom',
      capacity: 100,
      description: "Think you can outsmart a chatbot? Come experiment hands-on with real AI apps and try to break them — no coding required. We'll get hands-on with why AI safety is harder than it looks, why people are working hard to fix it, and how you can get involved! Materials: device.",
      classIndex: 57,
      zoomLink: 'https://illinois.zoom.us/j/86820870435?pwd=bSszEOjQs7E8NUusz9Ng3DqCTOUkQu.1',
    },
    {
      className: 'Getting Started with Research',
      time: '1:30pm-2:20pm',
      room: 'Zoom',
      capacity: 100,
      description: "This course is an introduction to getting started in research in the computing field. We will explore various research opportunities, share research grant resources, and discuss how research is an enriching experience that builds valuable skills, builds powerful connections, and paves way for a successful career.",
      classIndex: 58,
      zoomLink: null,
    },
    {
      className: '"Git" Gud at Version Control',
      time: '1:30pm-2:20pm',
      room: 'Zoom',
      capacity: 100,
      description: "Learn how to collaborate on projects large and small using Git, the industry standard tool for versioning and sharing code! This is a hands-on class where students will learn the fundamentals of the Git version control system, workflows and how to use it for collaboration and contributing to OSS. Materials: device.",
      classIndex: 59,
      zoomLink: "https://illinois.zoom.us/j/88661024310?pwd=JPwzMvv2HWaWaNXkcyB9AmBRAgGgJa.1",
    },
    {
      className: 'Beyond the Keyboard: Navigating Digital Tech Project Management',
      time: '1:30pm-2:20pm',
      room: 'Zoom',
      capacity: 100,
      description: "Ever wonder what project managers actually do? Join this interactive lesson to learn the basics of balancing time, quality, and cost! Through hands-on simulations and fun activities, you'll explore Agile, Scrum, Gantt charts, and popular software. Discover how to plan projects, uncover exciting career paths, and review salary expectations. Materials: device.",
      classIndex: 60,
      zoomLink: "https://illinois.zoom.us/j/6133787845?pwd=wRnBhiGrsruZzCJ2f2IzcNWtV3kXjT.1",
    },
    {
      className: 'Beyond the Classroom: Finding Your Community with RSOs in CS @ Illinois',
      time: '1:30pm-2:20pm',
      room: 'Zoom',
      capacity: 100,
      description: "CS at Illinois is much more than classes, office hours, and coding assignments. Some of the most meaningful parts of college happen when you find the people, projects, and communities that make campus feel like home. In this session, we'll explore the many ways students get involved in CS outside the classroom, from hackathons and project teams to mentorship programs, identity-based communities, and organizations beyond CS entirely.",
      classIndex: 61,
      zoomLink: 'https://illinois.zoom.us/j/82488677746?pwd=nLOU8wsvvJAfsDKDCugOY2ZmknMiKm.1',
    },
    {
      className: 'Breaking In & Standing Out',
      time: '1:30pm-2:20pm',
      room: 'Zoom',
      capacity: 100,
      description: "Learn how to break into the CS industry from two Google interns! Get an overview of what projects and resources to look out for, how to interview prep, and how to be successful at your internship! Some free swag will be provided thanks to the Google Ambassador Program. Please bring a resume if you wish for it to be reviewed. Materials: recommended resume.",
      classIndex: 62,
      zoomLink: "https://illinois.zoom.us/j/88686187936?pwd=aEsU8zx1sAzVVplavxmdiUva3MFfXR.1",
    },
    {
      className: 'Code Meets Cosmos',
      time: '1:30pm-2:20pm',
      room: 'Zoom',
      capacity: 100,
      description: "The Three-Body problem. Maybe you have watched the Netflix show or heard of this physics problem that stumps researchers today. In Code Meets Cosmos, we will simulate the Three-Body problem ourselves and see why it remains unsolved to this day. No prior physics knowledge is needed! Materials: device.",
      classIndex: 63,
      zoomLink: 'https://illinois.zoom.us/j/83999356166?pwd=L3UCxo3VO0ka6ucMua6nE7PJCm1fFV.1',
    },
    {
      className: 'Intro to Game Development w/ Roblox Studio',
      time: '1:30pm-2:20pm',
      room: 'Zoom',
      capacity: 100,
      description: "Ever wanted to know what kind of thinking goes into Game development? In this class, we provide a general introduction to game development concepts, including System Design, Raycasting, Anti-cheat, and State Machines, using Super Mario Bros. Level 1-1 as a case study. No knowledge of Roblox Studio required, but an understanding of programming is very helpful. Materials: device.",
      classIndex: 64,
      zoomLink: "https://illinois.zoom.us/j/3679837562?pwd=WpArGYv9KhwniLgG1vVZgfHOan1Z3x.1",
    },
    {
      className: 'From Domino Puzzles to Math and Computer Science',
      time: '1:30pm-2:20pm',
      room: 'Zoom',
      capacity: 100,
      description: "How many ways can you cover a chessboard with dominos? What if we roll that board into a cylinder or a donut? The results of domino tiling on different surfaces is well established, but results using more complex shapes are still active areas of research, with deep relations to other fields of Mathematics. This course aims to provide an overview of this field with rich examples and proof. Materials: paper and pen.",
      classIndex: 65,
      zoomLink: 'https://illinois.zoom.us/j/89773247468?pwd=eK62iAWIMOsGw5DGXUpZV23aSp9ybf.1',
    },
    {
      className: 'Intro to the Engineering Pathways Program',
      time: '1:30pm-2:20pm',
      room: 'Zoom',
      capacity: 100,
      description: "The Engineering Pathways Program is a community college transfer plan that offers guaranteed admission into the Grainger College of Engineering for your major of choice, including Computer Science. In this session, you'll learn about the application process, eligibility requirements and other important information. I'll also include advice from myself and other Pathways CS students about school and securing a successful career in tech.",
      classIndex: 66,
      zoomLink: "https://illinois.zoom.us/j/81158412041?pwd=pPrI8LcofwbnP5tXKJbEgvaE3UY9K3.1",
    },
    {
      className: 'Cybersecurity Ninja Training',
      time: '1:30pm-2:20pm',
      room: 'Zoom',
      capacity: 100,
      description: "Interested in cybersecurity or learning to \"hack\"? This course will introduce you to basic security (and ethics) concepts through an interactive demo where we will try to break into a system! Laptop not required, no prior experience necessary.",
      classIndex: 67,
      zoomLink: null,
    },

    // ==================== Added Classes ====================
    {
      className: "Running with the Bulls: Data Science in Sports Analytics",
      time: "2:00pm-2:50pm",
      room: "Siebel 2407",
      capacity: 20,
      description: "Become a Lead Data Scientist for the Chicago Bulls! In this interactive coding class, students will use Python and pandas to explore player datasets, respond to coaching requests, and build a winning roster. Through guided coding and data analysis, teams will compete to create the strongest draft class using real data science techniques.",
      classIndex: 68,
      zoomLink: null,
    },
  ];

  // {
  //   className: 'Intro to Search Engines',
  //   time: '11:00am-11:50am',
  //   room: 'Siebel 2406',
  //   capacity: 48,
  //   description: "Explore the system behind every search you make. We'll break down the three traditional steps; Crawl, Index, and Rank, and see why keyword matching is obsolete. Discover how Large Language Models (LLMs) like Gemini and ChatGPT are revolutionizing search by understanding context and intent, and examine the critical, unsolved problems of AI bias and hallucinations.",
  //   classIndex: 22,
  //   zoomLink: null,
  // },

  // {
  //   className: 'Quantum Computing for High Schoolers',
  //   time: '11:00am-11:50am',
  //   room: 'Siebel 0216',
  //   capacity: 93,
  //   description: "Learn what you need to know about an exciting revolution in technology! This course includes no mathematics or coding. Instead, enjoy exploring what quantum computing is actually about, the weird rules of quantum physics, and how this all changes computing in the future. We will also play a game from Google Quantum AI and have a casual Q&A! Materials: device.",
  //   classIndex: 17,
  //   zoomLink: null,
  // },

  // {
  //   className: 'Python Mosaic',
  //   time: '10:00am-10:50am',
  //   room: 'Siebel 3102',
  //   capacity: 14,
  //   description: "Materials: device, optional image dataset.",
  //   classIndex: 8,
  //   zoomLink: null,
  // },

   // {
   //   className: 'Python Mosaic',
   //   time: '2:00pm-2:50pm',
   //   room: 'Siebel 3102',
   //   capacity: 14,
   //   description: "Materials: device, optional image dataset.",
   //   classIndex: 42,
   //   zoomLink: null,
   // },

  //  {
  //   className: 'CS Explained Through Anime and Shows',
  //   time: '12:30pm-1:20pm',
  //   room: 'Zoom',
  //   capacity: 100,
  //   description: "Ever wanted to learn what Computer Science is all about? Well now you can learn about Computer Science through Anime and Shows! This will be a course where you get to talk about and learn from your favorite shows through the lens of Computer Science. Learn about how computer scientists think about problems! Materials: device.",
  //   classIndex: 51,
  //   zoomLink: 'https://illinois.zoom.us/j/83474597131?pwd=LzCfnbkxbavnPdo5aj7XDo8aP1qdXe.1',
  // },

  // {
  //   className: 'How Your Computer Lies to You: An Introduction to Numerical Analysis',
  //   time: '1:30pm-2:20pm',
  //   room: 'Zoom',
  //   capacity: 100,
  //   description: "This course will go over the basics of Numerical Analysis and is focused on making the topics approachable and interactive. It covers ways that computers misrepresent information, approximation methods, optimization, and also a bit of advice for prospective college students. Materials: optional note-taking materials.",
  //   classIndex: 56,
  //   zoomLink: null,
  // },

  // {
  //   className: 'Cybersecurity Ninja Training',
  //   time: '10:00am-10:50am',
  //   room: 'Siebel 0218',
  //   capacity: 47,
  //   description: "Interested in cybersecurity or learning to \"hack\"? This course will introduce you to basic security (and ethics) concepts through an interactive demo where we will try to break into a system! Laptop not required, no prior experience necessary.",
  //   classIndex: 1,
  //   zoomLink: null,
  // },

  // {
  //   className: 'Cybersecurity Ninja Training',
  //   time: '2:00pm-2:50pm',
  //   room: 'Siebel 0218',
  //   capacity: 47,
  //   description: "Interested in cybersecurity or learning to \"hack\"? This course will introduce you to basic security (and ethics) concepts through an interactive demo where we will try to break into a system! Laptop not required, no prior experience necessary.",
  //   classIndex: 35,
  //   zoomLink: null,
  // },
    
  
  allClasses.forEach((c) => {
    if (!c.zoomLink) {
      c.zoomLink = null;
    }
  });
  
  allClasses.forEach((c, i) => c.index = i);
  
  const inPersonMorningClassesFirst = allClasses.filter(c => c.time === '10:00am-10:50am');
  const inPersonMorningClassesSecond = allClasses.filter(c => c.time === '11:00am-11:50am');
  const inPersonAfternoonClasses = allClasses.filter(c => c.time === '2:00pm-2:50pm');
  const virtualMorningClasses = allClasses.filter(c => c.time === '12:30pm-1:20pm');
  const virtualAfternoonClasses = allClasses.filter(c => c.time === '1:30pm-2:20pm');
  
  export { inPersonMorningClassesFirst, inPersonMorningClassesSecond, inPersonAfternoonClasses, virtualMorningClasses, virtualAfternoonClasses };
  export default allClasses;