# Generated by Django 4.1.4 on 2023-03-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_sailuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sailuser',
            name='dietary_restrictions',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sailuser',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sailuser',
            name='gender_identification',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary', 'Non-binary')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='sailuser',
            name='home_zip_code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='sailuser',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sailuser',
            name='parent_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sailuser',
            name='parent_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sailuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender_identification',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary', 'Non-binary')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(max_length=20),
        ),
    ]
